book_collection/config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  match 'about', to: "main#about", via: :get
  match 'hello', to: "main#hello", via: :get

  get 'main/index'

  resources :books do
    member do
      get :delete
    end
  end

  # get 'tasks/index'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/show'
  # get 'tasks/delete'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

book_collection/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

book_collection/app/models/book.rb
class Book < ApplicationRecord
end

book_collection/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

book_collection/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(:author)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new()
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
      flash.alert = "Added " + @book.title + " to the collection!"
    else
      render('new')
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash.alert = "Edited " + @book.title + " details."
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    btitle = @book.title
    @book.destroy
    redirect_to books_path
    flash.alert = "Removed " + btitle + " from the collection."
  end

  private
  def book_params
    params.require(:book).permit(
      :title,
      :author,
      :price,
      :published_date
    )
  end
end

book_collection/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
    @created_by = "Will Miranda"
    @id = params['id']
    @page = params[:page]
  end

  def hello
    redirect_to(action: 'index')
  end
end

book_collection/app/helpers/application_helper.rb
module ApplicationHelper
end

book_collection/app/helpers/books_helper.rb
module BooksHelper
end

book_collection/app/helpers/main_helper.rb
module MainHelper
end

book_collection/app/views/books/_form.html.erb
<table summary="Book form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.text_field(:price) %></td>
  </tr>
  <tr>
    <th>Date Published</th>
    <td><%= f.text_area(:published_date) %></td>
  </tr>
</table>

book_collection/app/views/books/delete.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

book_collection/app/views/books/edit.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit Book</h2>

  <%= form_for(@book) do |f| %>
    <% # url: book_path(@book), method: 'patch' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Edit Book") %>
    </div>

  <% end %>
</div>

book_collection/app/views/books/index.html.erb
<%= link_to('Back to Homepage', {controller: 'main', action: 'index'}) %><br />

<div class="books index">
  <h2>Books</h2>

  <%= link_to("Add New Book", new_book_path, class: 'action new') %>

  <table class="listing" summary="Book list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.price %></td>
      <td><%= book.published_date %></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
  <br/>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
</div>

book_collection/app/views/books/new.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>
    <% # url: books_path, method: 'post' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

book_collection/app/views/books/show.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books show">
  <h2>Show book</h2>

  <div class="actions">
    <%= link_to('Edit', edit_book_path(@book)) %>
    <%= link_to('Delete', delete_book_path(@book)) %>
  </div>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Date Published</th>
      <td><%= @book.published_date %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

book_collection/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

book_collection/app/views/main/about.html.erb
<h2>About</h2>

<p>Description of the Book Collection.</p>
<p>Created by <%= @created_by %></p>

ID: <%= @id %><br />
Page: <%= @page %><br />

book_collection/app/views/main/index.html.erb
<h1>Book Collection</h1>
<p>This is an application for managing a book collection.</p>

<%= link_to('Books', books_path) %><br />

<%= link_to('About', {action: 'about', page:5}) %><br />